/** Une entrée de « notes de version » affichée dans le menu principal. */
export interface PatchNote {
  version: string
  date: string
  title: string
  changes: string[]
}

/** Historique des changements, du plus récent au plus ancien. */
export const PATCH_NOTES: PatchNote[] = [
  {
    version: '0.74',
    date: '2026-06-19',
    title: 'Nouveau vilain : Sombra + finitions de Ratigan',
    changes: [
      'NOUVEAU VILAIN — Sombra (collaboration, 2★) : pirate les 4 lieux puis joue Protocole Sombra pour gagner. Mécanique de Piratage (désactive une action du lieu, overlay « hack » glitché + bruitage), Lumérico déverrouillé par Faille, Boop! qui pirate un Héros (capacité annulée), Invisibilité, et tout le deck Fatalité (l’Œil, Zarya, Guillermo, Lynx, Shutdown, Réinitialisation…).',
      'Sabotage (Fatalité de Ratigan) : le joueur qui la pose choisit l’Objet (coûtant 3 ou moins) à défausser parmi les Objets situés sur un lieu occupé par un Héros — ce qui détermine aussi le lieu. Le bot vise l’Objet le plus cher.',
      'Ballon de fortune (Fatalité de Ratigan) : le joueur qui la pose choisit le Héros à équiper (+2 Force), puis peut OU NON le déplacer — et s’il le déplace, il choisit librement le lieu (n’importe lequel). Le Ballon suit le Héros.',
      'Appel à l’aide (Fatalité de Ratigan) : le joueur qui la pose choisit désormais le lieu où Basil apparaît (ou se déplace, s’il est déjà en jeu) — une fenêtre propose les quatre lieux. Le bot vise le lieu de la Reine Robot (pour la faire défausser), sinon Buckingham Palace.',
      'Cloche : ne peut plus être activée si Félicia est déjà dans votre main ou déjà posée sur un lieu (elle serait sans effet). L’action « Activer » se grise dans ce cas.',
      'Extravagance : Condition jouable en réaction quand un adversaire gagne au moins 3 jetons Pouvoir — choisissez alors un Objet de votre défausse à ajouter à votre main (une fenêtre vous laisse choisir lequel).',
      'Sournois : Condition jouable en réaction quand un adversaire vous cible avec une Fatalité — il ne dévoile alors qu’une seule carte Fatalité au lieu de deux (la carte en trop retourne sur le dessus de votre pioche).',
      'Liste de Fidget : en la jouant, vous dévoilez les cartes du dessus de votre pioche jusqu’à tomber sur un Objet. Cet Objet rejoint votre main, les autres cartes dévoilées sont défaussées — et une fenêtre vous montre TOUTES les cartes dévoilées (l’Objet gardé est surligné), à refermer d’un clic sur « Compris ».',
      'Piège ingénieux : quand le piège se referme au début de votre tour, les Héros éliminés s’affichent désormais (animation de défausse) au lieu de disparaître silencieusement.',
      'Capture : plus de fenêtre séparée pour choisir le Héros — cliquez directement le Héros voulu sur le plateau (il clignote en ambre) pour l’envoyer au Repaire secret. La carte est désormais injouable s’il n’y a aucun Héros de force 3 ou moins ailleurs qu’au Repaire secret, et un Héros déjà sur le Repaire secret n’est plus proposé comme cible.',
    ],
  },
  {
    version: '0.73',
    date: '2026-06-18',
    title: 'Ratigan : Engrenages, Grand Génie du Mal, Habits royaux, Félicia',
    changes: [
      'Lorsque vous posez un Objet et que des Engrenages sont en jeu, plus de fenêtre séparée : cochez directement les Engrenages à défausser sur le plateau (surlignés en ambre). Le coût se met à jour en direct et un bouton « Poser » confirme la pose.',
      'Le Grand Génie du Mal vous laisse désormais choisir : piocher 2 cartes OU gagner 2 jetons Pouvoir (une fenêtre propose les deux options). Le bot tranche selon sa main.',
      'Habits royaux devient un Objet à activer : posez-le, puis utilisez une action « Activer » pour gagner 2 jetons Pouvoir (réutilisable chaque tour) au lieu d’un gain unique à la pose.',
      'Félicia : à la pose, vous choisissez entre défausser un Allié de son lieu ou payer 2 jetons Pouvoir de plus. S’il y a plusieurs Alliés, vous cliquez celui à défausser. Si vous ne pouvez ni défausser un Allié ni payer le supplément, la carte est injouable sur ce lieu.',
      'Uniforme : après l’avoir associé à un Allié (+2 Force), vous pouvez enchaîner une action « Éliminer un Héros » sur le lieu de cet Allié — qui doit obligatoirement participer (il est présélectionné). Action facultative : un bouton « Terminer » permet d’y renoncer.',
      'Brutes : jouées sur un lieu où votre pion n’est PAS, elles vous laissent désormais effectuer librement UNE action disponible de ce lieu (hors Fatalité) — au lieu de simplement gagner du Pouvoir. Un bandeau « Brutes » s’affiche avec un bouton « Passer » pour y renoncer.',
      'Capture : quand plusieurs Héros de force 3 ou moins sont en jeu, vous choisissez désormais lequel envoyer au Repaire secret (au lieu d’un choix automatique).',
      'Positions des pastilles d’action du plateau de Ratigan corrigées (elles tombent désormais pile sur les icônes des quatre lieux).',
    ],
  },
  {
    version: '0.72',
    date: '2026-06-18',
    title: 'Bot plus malin (Fatalité, objectifs) + confort de jeu',
    changes: [
      'Progression d’objectif : chaque camp affiche désormais une barre de progression (en %) vers sa victoire, calculée selon la vraie proximité de l’objectif.',
      'Bot — Fatalité plus juste : il ne s’acharne plus à vous fataliser quand vous êtes déjà bien gêné/bloqué (il se concentre alors sur son objectif), et fatalise fort quand vous foncez vers la victoire. Si vous avez atteint votre objectif et attendez votre prochain tour, il tente systématiquement de vous fataliser.',
      'Bot — il évite de vous rendre service : il ne lance pas de Fatalité si cela vous donnerait votre Héros-clé encore absent (Mufasa pour Scar, Peter Pan pour Crochet, Peach pour Bowser, Blanche-Neige pour la Méchante Reine, Kuzco pour Yzma).',
      'Bot — Bowser : il rassemble enfin ses Alliés à l’Observatoire de la Comète pour drainer les Étoiles. Reine de Cœur : il transforme ses Cartes Gardes en arceaux. Jauges d’objectif affinées (Crochet, Yzma, Ratigan…).',
      'Modale de Fatalité : un bouton « Défausse Fatalité » pour consulter la défausse de la cible, et un bouton « Voir le plateau » (à maintenir enfoncé) qui masque la modale le temps de regarder le plateau.',
      '« Te revoilà ! » (Bowser) : on choisit la carte à récupérer directement dans la défausse (modale défilable), au lieu d’une liste tronquée.',
      'Bowser : on ne peut plus activer Bowser Jr. une fois Peach en jeu ou capturée. Flèche de Mome Raths (Reine de Cœur) : déplace bien un Allié vers le lieu choisi.',
      'Cinématique d’intro : son réglé sur le volume de la musique des Options (et forcé à un niveau audible si la musique est coupée).',
    ],
  },
  {
    version: '0.71',
    date: '2026-06-17',
    title: 'Nouveau vilain : Ratigan (+ bouton Cinématique)',
    changes: [
      'Nouveau vilain jouable : Ratigan (Basil, détective privé) — Disney, difficulté 2★. Plateau (Repaire secret, Magasin de Flaversham, Big Ben, Buckingham Palace), pion, portrait et présentation, dos de cartes, fiche et conseils, 30 cartes Méchant + 15 Fatalité avec leurs illustrations.',
      'Objectif double : jouez la Reine Robot et postez-la à Buckingham Palace pour gagner — mais si Basil la défausse, Ratigan « devient le Rat » et doit alors éliminer Basil. La Reine Moustoria à Buckingham Palace bloque la victoire dans les deux cas.',
      'La tuile Objectif est posée sur le plateau (panneau gauche) : côté « L’Esprit Supérieur » au départ, elle se retourne automatiquement côté « Le Rat » quand la Reine Robot est défaussée.',
      'Reine Robot (coût 15) rendue atteignable : Engrenages (défaussés, −3 chacun), Outils (−1) et Flaversham sur le Repaire secret (−3) réduisent son coût.',
      'Toutes les cartes de Ratigan sont désormais actives. Méchant : Capture (déplace un Héros ≤3 au Repaire secret), Fidget (fait venir Flaversham), Cloche (Activer : récupère Félicia), Dirigeable (Activer : transporte un Objet/Allié n’importe où — idéal pour amener la Reine Robot à Buckingham), Piège ingénieux (Activer : au début de votre tour suivant, élimine tous les Héros de son lieu — peut éliminer Basil), Félicia (défausse un Héros de son lieu, sinon +2), Brutes (jouées à distance : profitent d’une action « Gagner » du lieu), Liste de Fidget, Le Grand Génie du Mal, Habits royaux, Uniforme (+2).',
      'Côté Fatalité : Basil défausse la Reine Robot (déclenche « Le Rat »), Appel à l’aide fait venir Basil, Sabotage défausse un Objet bon marché, Toby et Ballon de fortune déplacent un Héros, Olivia dévoile/joue une Fatalité à sa mort, Mrs. Judson draine 2 Pouvoir, Dr. Dawson gagne +2 si Basil est là.',
      'Un bouton « 🎬 Cinématique » apparaît en bas à gauche du menu principal : il rejoue à volonté la cinématique d’introduction (qui reste passable via Échap).',
    ],
  },
  {
    version: '0.70',
    date: '2026-06-17',
    title: 'Cinématique d’introduction + mémorisation de l’affichage',
    changes: [
      'Au lancement du jeu, une cinématique « Les Méchants Disney se déchaînent » est désormais jouée en plein écran avant le menu principal. À la fin de la vidéo, un fondu au noir laisse place au menu.',
      'La cinématique peut être passée à tout moment en appuyant sur Échap (ou en cliquant sur « Passer »). Son volume a été légèrement baissé.',
      'Elle ne se joue qu’une fois par lancement : un simple rechargement de la fenêtre ne la rejoue pas.',
      'Affichage : le jeu se lance désormais dans le mode choisi dans les Options (fenêtré / plein écran), mémorisé d’un lancement à l’autre. Au tout premier lancement, le jeu démarre en plein écran.',
    ],
  },
  {
    version: '0.69',
    date: '2026-06-17',
    title: 'Yzma — corrections de cartes (Beauté endormie, Le chemin qui balance)',
    changes: [
      'Yzma — Beauté endormie : la carte ne reste plus surlignée à tort. Comme elle ne peut être jouée qu’en PREMIÈRE et SEULE action du tour, elle est maintenant grisée dès que vous avez déjà fait une action (vous ne pouvez donc plus cliquer dessus pour rien). Après l’avoir jouée, plus aucune autre action n’est possible ce tour-ci (seul « Fin de tour » reste).',
      'Yzma — Beauté endormie : l’effet du tour suivant est désormais complet et au choix. Avant de vous déplacer, une fenêtre vous laisse décider, indépendamment, de gagner 2 Pouvoir, de piocher 2 cartes et de déplacer un Héros de votre royaume vers un lieu voisin (le seul moyen pour Yzma de déplacer Kuzco). Vous pouvez tout faire, une partie, ou rien.',
      'Yzma — Le chemin qui balance : la carte est maintenant grisée (injouable) s’il n’y a aucun jeton Pouvoir sur Kronk (Kronk absent du royaume ou sans jeton) — on ne peut plus la gaspiller pour rien.',
      'Yzma — Kuzco : éliminé SANS Kronk, il ne reste plus à tort dans la défausse Fatalité. Comme le veut sa règle, il est désormais remélangé avec toutes les cartes des 4 pioches Fatalité, puis celles-ci sont reformées le plus également possible (le déclenchement manquait après une élimination).',
      'Yzma — Fausses funérailles : la carte est maintenant grisée (injouable) s’il n’y a aucun Héros dans votre défausse Fatalité (elle ne rapporterait aucun jeton).',
      'Yzma — Finis le travail : on choisit désormais l’Allié à déplacer en cliquant DIRECTEMENT dessus sur le plateau (cartes surlignées), au lieu d’une liste où deux Alliés identiques (ex. deux « Gardes du palais ») étaient impossibles à distinguer. Le choix du lieu de destination (parmi tous les lieux portant un Héros) reste ensuite proposé.',
      'Yzma — Kronk : les jetons Pouvoir posés sur lui s’affichent maintenant sur sa carte (badge 🪙). Ils s’accumulent à chaque déplacement et, à 3 jetons, Kronk devient un Héros — c’est désormais visible. (Kronk reste conservé, comme avant, quand il sert à éliminer un Héros.)',
      'Yzma — Kronk : s’il est éliminé alors qu’il est devenu un Héros, il rejoint la défausse Méchant (et redevient un Allié normal), au lieu de la défausse Fatalité.',
      'Yzma — Bras droit : quand Kronk est dans votre royaume (y compris devenu Héros), il est désormais bien RETIRÉ du plateau et ajouté à votre main (jetons Pouvoir défaussés, Objets associés repris en main, transformation annulée). Avant, il restait à tort sur le plateau.',
      'Correctif général : un Objet associé (ex. Couteau sur un Allié) n’intercepte plus le clic destiné à sa carte porteuse. On peut donc de nouveau sélectionner un Allié équipé pour éliminer un Héros (ex. Gardes impériaux + Couteau contre Bucky).',
    ],
  },
  {
    version: '0.68',
    date: '2026-06-17',
    title: 'Profil joueur : avatar et nom, affichés en partie et dans l’historique',
    changes: [
      'Profil : nouvel avatar personnalisable — choisissez un vilain (son illustration de présentation) et une couleur de fond parmi une palette (noir par défaut, et blanc disponible). Saisissez aussi votre nom de joueur (« Toi » par défaut).',
      'L’écran Profil affiche maintenant l’avatar en grand, centré, avec le nom dessous et un petit bouton crayon pour basculer en mode édition. Les statistiques par vilain passent d’une liste à une grille.',
      'Menu principal : le bouton « Mon profil » devient votre avatar (en bas à droite, près des Options), légèrement estompé et qui s’éclaircit au survol.',
      'Choix des vilains : en solo comme en réseau, votre camp affiche désormais votre nom de joueur ; en réseau, le camp adverse affiche le nom de l’autre joueur.',
      'En partie : le panneau de votre camp affiche votre nom ; le panneau adverse affiche le nom du vilain en solo, ou le nom de l’autre joueur en réseau.',
      'Historique des parties : avatars ronds et noms. En solo, votre avatar/nom face au vilain adverse (image + couleur du vilain) ; en réseau, les deux noms et avatars des joueurs.',
      'Rejoindre une partie : un bouton « Annuler » permet de stopper une tentative de connexion (ex. mauvais code) et de corriger le code sans repasser par le menu.',
    ],
  },
  {
    version: '0.67',
    date: '2026-06-15',
    title: 'Nouvelle méchante : La Méchante Reine, sons d’interface et ajustements',
    changes: [
      'Nouveau méchant Disney : Scar (Le Roi Lion, 4 étoiles) — plateau (Rocher des lions, Savane, Cimetière d’éléphants, Gorge, tous actifs dès le début), pion, decks complets et voix. Sa pile SUCCESSION (à gauche du plateau) accueille Mufasa puis les Héros éliminés ensuite : atteins-y 15 de Force combinée pour gagner. (Première étape : sélection, plateau et cartes en place ; la pile Succession et les effets de cartes spécifiques arrivent ensuite.)',
      'Nouvelle méchante Disney : La Méchante Reine (3 étoiles) — plateau (Laboratoire, Forêt, Mine, Maison des Nains), deck complet et voix. Préparez du Poison, jouez les 4 Ingrédients pour déverrouiller la Maison des Nains, faites venir Blanche-Neige avec le Miroir magique puis éliminez-la avec « Croque ! ». Zone Ingrédients et jetons Poison affichés dans son panneau.',
      'L’Imposteur passe à 3 étoiles ; Bowser passe à 4 étoiles.',
      'L’écran « Liste des vilains » a maintenant sa propre musique de fond (au lieu de la musique du menu), à un volume légèrement plus bas.',
      'Petit son d’appui sur le bouton « Fermer » de la fiche d’un vilain.',
      'Bouton « Fermer » des Options : petit son d’appui au clic et son de survol au passage du curseur.',
      'Son de sélection en cliquant sur un vilain dans la liste.',
      'Écran « Nouvelle partie » : son de retour au clic sur « ← Menu » et son de survol au passage du curseur, et son d’appui / de survol sur les boutons « Partie en solo », « Héberger une partie » et « Rejoindre une partie ».',
      'Écran « Choix des vilains » : son de sélection au clic sur « Lancer la partie » et son de survol au passage du curseur ; le bouton « ← Menu » a les mêmes sons que sur « Nouvelle partie » ; clic et survol d’un vilain utilisent les mêmes sons que dans la liste des vilains.',
      'Menu principal : son de survol dédié sur le bouton « Mon profil ».',
      'En partie : alerte sonore « À vous de jouer » au début de votre tour (sauf si vous incarnez L’Imposteur, qui garde son ambiance Among Us).',
      'En partie : son dédié au clic sur le bouton « Fin de tour », et un son quand ce bouton devient utilisable (passe de grisé à actif).',
      'En partie : son de survol sur les boutons « Menu » et « Options » ; le bouton « Menu » (solo) demande désormais une confirmation avant de quitter la partie (Annuler / Quitter).',
      'En partie : son dédié quand on ouvre une défausse (Vilain ou Fatalité) ou la Pile de l’Au-delà pour regarder dedans.',
      'Prince Jean : « Magnifiques Taxes » ne peut plus être jouée s’il n’y a aucun Héros dans votre royaume (elle n’aurait aucun effet).',
      'Slenderman : « Tombée de la nuit » — si plusieurs cartes du type choisi (Événement ou Objet) sont dévoilées, vous choisissez désormais laquelle ajouter à votre main.',
      'La Méchante Reine — Foudre : son coût est maintenant égal à celui de l’Ingrédient reproduit (payé au moment du choix). Elle ne propose que les Ingrédients que vous pouvez payer, et reste injouable si aucun ne l’est.',
      'La Méchante Reine — « Préparer du poison » : l’action convertit désormais autant de jetons Pouvoir que vous voulez en jetons Poison (1 pour 1), via un petit sélecteur. Elle est indisponible si vous n’avez aucun Pouvoir à convertir ; avec Timide en jeu, utiliser l’action coûte 1 Pouvoir de plus (perdu).',
      'Correction Blanche-Neige : dévoilée par la Fatalité adverse, elle est désormais jouée d’office sur la Maison des Nains (et l’autre carte dévoilée est défaussée). Elle était auparavant placée sur un lieu inexistant et n’apparaissait nulle part.',
      'Correction d’affichage : un Héros posé sur un lieu verrouillé est maintenant bien visible — le voile « verrouillé » passe sous les Héros au lieu de les masquer. L’info-bulle du cadenas affiche le bon nom de lieu.',
      'La Méchante Reine — Dormeur : s’il fait partie des deux cartes dévoilées par une Fatalité, vous pouvez désormais jouer les DEUX cartes (la seconde reste facultative : un bouton « Passer » permet de ne pas la jouer). Même règle harmonisée pour Ray (Dr Facilier).',
      'La Méchante Reine — Animaux de la forêt : la main de la cible est désormais révélée et c’est le joueur qui pose la Fatalité qui choisit la carte à défausser (au lieu d’un choix automatique).',
      'La Méchante Reine — Premier baiser d’amour : retire 1 Poison à la Méchante Reine, puis le joueur qui pose la Fatalité choisit lui-même quel Héros de la défausse Fatalité revient sur le dessus de la pioche Fatalité. La carte est grisée (injouable) si la Méchante Reine n’a ni Poison ni Héros dans sa défausse Fatalité.',
      'La Méchante Reine — « Croque ! » est maintenant injouable (grisée) s’il n’y a aucun Héros éliminable sur votre lieu (pas assez de Poison pour sa force, ou priorité Prof non respectée) : on ne peut plus la gaspiller dans le vide.',
      'Début de partie : le jet de dés « Qui commence ? » apparaît maintenant APRÈS la présentation des deux joueurs (l’écran « X contre Y ») et seulement une fois la voix d’intro adverse terminée, au lieu de se lancer pendant. Nouveaux bruitages calés pour jouer en entier (sans être coupés) : apparition du panneau de dés, boucle pendant que les dés tournent, son d’annonce du résultat (y compris sur une égalité, avant la relance), et son de disparition de l’écran. À la fin, l’écran ne se ferme plus d’un coup : il s’efface progressivement pendant que les portraits des vilains rejoignent leur plateau (transition calée sur le son de disparition).',
      'Un jingle retentit à l’apparition de l’écran de fin (un pour la VICTOIRE, un autre pour la DÉFAITE).',
      'Écran de DÉFAITE : juste après son apparition, le mot « DÉFAITE » s’incline lourdement à 45° vers le bas (effet dramatique).',
      'Fin de partie : avant l’écran Victoire/Défaite, le plateau du perdant se couvre lentement de grosses fissures blanches qui se propagent depuis le point d’impact, puis vole en éclats comme un miroir brisé (inspiration Hearthstone : fissures + flash, puis éclats projetés à travers l’écran). Une musique de montée (différente en victoire et en défaite) démarre dès la fissure et l’écran de fin arrive sur sa ~4,9ᵉ seconde ; un bruit d’explosion accompagne l’éclatement. (Mode test : boutons 🏆 Victoire / 💀 Défaite pour rejouer toute la séquence éclat → écran.)',
    ],
  },
  {
    version: '0.66',
    date: '2026-06-15',
    title: 'Décor animé en arrière-plan (Bowser : bateau volant)',
    changes: [
      'Chaque méchant peut désormais avoir une animation de décor qui apparaît de temps en temps en arrière-plan pendant la partie (derrière le plateau).',
      'Bowser : son bateau pirate volant décolle de la pile Fatalité, s’élève au-dessus du compteur de tours et disparaît dans le ciel.',
      'En mode test, deux boutons 🚢 permettent de rejouer l’animation de chaque méchant à la demande.',
    ],
  },
  {
    version: '0.65',
    date: '2026-06-14',
    title: 'Bowser : finitions (Étoiles, Bateau, Grand Terrier) et bouton Options',
    changes: [
      'Bowser — Grand Terrier : à sa pose, vous pouvez déplacer un de vos Alliés vers un lieu voisin (ou décliner).',
      'Bowser — Bateau : même fonctionnement que le Char d’Hadès — sur son lieu, déplacez votre figurine et le Bateau vers n’importe quel lieu pour y faire une action (hors Fatalité), une fois par tour.',
      'Les Étoiles sont maintenant visibles : sur l’Observatoire de la Comète (entre les deux rangées d’actions) et sur les Alliés qui en portent une (jeton + contour orange).',
      'Correction « Vous avez obtenu une grande étoile ! » : la carte reprend désormais réellement une Étoile posée sur un de vos Alliés pour la remettre sur l’Observatoire (rien ne se passe si aucun Allié n’en a). Une Étoile sur un Allié défaussé est définitivement perdue.',
      'Les Fatalités-Événement de Bowser (grande étoile, Goinfre, Comète farceuse, Anneau étoile) s’affichent maintenant en grand quand l’adversaire les joue.',
      'Correction Galaxie en verre : son action « Déplacer un objet ou un allié » fonctionne désormais (le clic sur le lieu voisin était sans effet).',
      'Nouvelles illustrations de Bowser (pion et présentation) et couleurs ajustées.',
      'Nouveau bouton Options (engrenage) en bas à droite des écrans hors-partie ; l’illustration du vilain apparaît derrière sa fiche détaillée ; le lobby réseau reprend le fond animé du menu.',
    ],
  },
  {
    version: '0.64',
    date: '2026-06-14',
    title: 'Nouveau méchant collaboration : Bowser (Super Mario Galaxy)',
    changes: [
      'Bowser rejoint la liste des méchants, dans la catégorie « Collaborations » (deck de 30 cartes Méchant + 15 Fatalité, thème Super Mario Galaxy).',
      'Son plateau : Château de Bowser, Galaxies, Observatoire de la Comète et Château de Peach.',
      'Mécanique des Étoiles : l’Observatoire de la Comète démarre avec 4 Étoiles. Objectif de Bowser : épuiser l’Observatoire (0 Étoile) ET capturer Peach (uniquement via la carte « Impuissance ») au début de son tour.',
      'Tant qu’il reste au moins une Étoile à l’Observatoire, ce lieu reste ouvert ; à 0 Étoile, il se bloque.',
      '« épuisement d’énergie » draine une Étoile de l’Observatoire vers un de vos Alliés présents (vous choisissez lequel).',
      'Contre-jeu (Fatalité) : Mario remet une Étoile et empêche la victoire tant qu’il est en jeu ; Harmonie force l’Observatoire à garder au moins une Étoile ; Luigi défausse les Alliés d’un lieu et renvoie leurs Étoiles ; Goinfre, Comète farceuse et Anneau étoile gênent Bowser.',
      'Cartes spéciales : Bowser Jr. (va chercher Peach, et vous fait piocher quand vous êtes visé par la Fatalité), Galaxie hantée et autres capacités à « Activer », « Te revoilà ! » (récupération en défausse), « Vol du château » et « Besoin de renfort ».',
      'À venir pour Bowser : le déplacement spécial du Bateau et le déplacement d’Allié du Grand Terrier (ces cartes se jouent déjà comme Objet / Allié).',
    ],
  },
  {
    version: '0.63',
    date: '2026-06-14',
    title: "Nouveau méchant : L'Imposteur (Among Us)",
    changes: [
      "Nouveau méchant jouable dans « Collaborations » : L'Imposteur (4 étoiles), avec son plateau (Electrical, Réacteur, Admin, Cafétaria), son deck complet et ses voix.",
      'Mécanique des Coéquipiers : 8 pions occupent la rangée du haut. À la fin de votre tour, ils se déplacent tout seuls (ils foncent vers un sabotage, sinon vers une tâche, sinon ils se répartissent). Un Coéquipier « suspect » descend sur une action et la bloque, comme un héros.',
      'Objectif : posez un Sabotage (O2 à Admin, Réacteur au Réacteur) et tenez-le 3 tours. Mais si assez de Coéquipiers atteignent une Tâche ou un Sabotage, la carte est neutralisée.',
      'Vos cartes manipulent les Coéquipiers : Tuer (élimine, les autres vous suspectent), Fausse accusation, Assurance (rend normal + déplace), Porte/Lumière/Communication désactivée, Conduit, les Tâches (capacité « Activer ») et les deux Sabotages.',
      'La Fatalité contre l’Imposteur ne contient pas de héros : ce sont des Coéquipiers et des indices (Corps découvert, Vidéo de surveillance, Carte, Majorité, Réparation rapide, Tâche visuelle, Arrivée tardive, Réunion d’urgence) qui le démasquent — avec choix interactifs des cibles/lieux.',
      'Ambiance Among Us : musique de tour, alarme de sabotage, sons « kill » / « task complete », et écrans « DEAD BODY REPORTED » et « EMERGENCY MEETING ».',
    ],
  },
  {
    version: '0.62',
    date: '2026-06-14',
    title: 'Application de bureau (.exe) et multijoueur sur le réseau local',
    changes: [
      'Le jeu peut désormais être lancé comme un vrai logiciel Windows (fichier .exe / installeur), sans navigateur ni ligne de commande.',
      'Affrontez un autre joueur sur le même réseau local. Depuis « Nouvelle partie », trois choix : « Partie en solo » (contre le bot), « Héberger une partie » ou « Rejoindre une partie ».',
      'Multijoueur intégré à l’application : plus besoin de lancer un serveur à part. Quand vous hébergez une partie, l’app démarre toute seule le serveur de liaison et affiche votre adresse réseau (IP) à communiquer à l’autre joueur.',
      'Pour rejoindre : sur l’autre PC, ouvrez Villainous, choisissez « Rejoindre une partie », puis saisissez l’adresse (IP) de l’hôte et le code de salon à 4 lettres.',
      'À la première partie en réseau, Windows peut demander d’autoriser l’application sur le réseau : acceptez (réseaux privés) pour que l’autre joueur puisse se connecter.',
      'Choix des vilains en direct : une fois connectés, les deux joueurs choisissent leur vilain sur le même écran et voient le choix de l’autre en temps réel ; un vilain déjà pris est grisé (pas de doublon). L’hôte lance ensuite la partie.',
      'En jeu : écran « versus » au lancement (avec la voix d’intro), point de vue relativisé (chacun se voit en haut, avec SON méchant sur ses affiches), et le plateau se synchronise en direct — seul le joueur dont c’est le tour peut agir, l’autre suit.',
      'Conditions en réaction : jouez vos Conditions (Avarice, Lâcheté…) pendant le tour adverse ; si elles demandent un choix (Allié, Héros, lieu), l’adversaire patiente avec « {méchant} joue une condition ! » jusqu’à la résolution.',
      'Bouton « Quitter » (avec confirmation) : l’autre joueur est prévenu et renvoyé à l’accueil, et le salon est libéré ; une coupure de connexion est gérée de la même façon.',
      'Limites de cette version : l’hôte commence toujours (pas de jet de dé ni de compensation en réseau), et la reconnexion n’est pas encore gérée.',
    ],
  },
  {
    version: '0.61',
    date: '2026-06-13',
    title: 'Mise en scène : versus, « À vous de jouer », animations',
    changes: [
      'Début de partie : écran « versus » animé (votre méchant — CONTRE — l’adversaire, illustrations en grand) qui accompagne la voix d’intro et le jet de dé pour savoir qui commence (~6 s).',
      'À chaque début de votre tour, une affiche « À vous de jouer » présente votre méchant.',
      'Nouveau thème de fond « teinté par les méchants » : les couleurs des deux vilains en présence colorent l’écran (avec une légère animation), en partie comme au choix des vilains.',
      'Les couleurs bleu/rouge (vous/adversaire) sont remplacées partout par la couleur de chaque méchant (panneaux, cartes-lieux, contours du plateau).',
      'Écran « Choix des vilains » : l’illustration du vilain sélectionné s’affiche en grand à gauche (vous) et à droite (adversaire) ; une silhouette mystère apparaît pour « Aléatoire » ; fond et bandeau du bas harmonisés.',
      'En-tête de partie épurée (transparente, sans titre). Le numéro affiché correspond désormais à une manche complète (les deux joueurs ont joué) et un chronomètre indique la durée de la partie.',
      'La carte sélectionnée garde son cadre jaune le temps de choisir sa cible ; vos actions de lieu s’illuminent au clic (comme celles du bot).',
      'Le déplacement d’une carte d’un lieu à l’autre est désormais animé (bot comme joueur).',
      'Pioche : les cartes apparaissent une par une et les cartes en vol passent derrière la main. Le showcase de défausse est plus court et n’a plus de petit décalage à l’apparition.',
      'Pendant une défausse, le bouton « Fin de tour » est remplacé par un bouton bleu « Défausser » ; le bouton « Annuler » est en rouge.',
      'Chaque écran a maintenant sa propre adresse (le lien change selon la page).',
      'Correctif bot : Hadès ne joue plus « Préparez-vous au combat ! » s’il n’a aucun Titan déplaçable.',
    ],
  },
  {
    version: '0.60',
    date: '2026-06-13',
    title: 'Nouveau vilain : Dr Facilier',
    changes: [
      'Dr Facilier (Disney, 2★) jouable : objectif « jouer le Talisman et Régner sur la Nouvelle-Orléans, détenir le Talisman, puis jouer Divination au Royaume du vaudou pour révéler Régner depuis la Pile de l’Au-delà ». Pion détouré, plateau, 30 cartes Méchant + 15 Fatalité, fiche et conseils, voix d’intro.',
      'Nouvelle mécanique : la Pile de l’Au-delà (visible sous le plateau, cliquable pour voir son contenu). Amis de l’au-delà et Régner y vont quand on les joue ; les adversaires l’alimentent via la Fatalité. Divination la mélange, en révèle 3 cartes (2 avec Mama Odie) et résout leurs effets dans l’ordre que vous choisissez.',
      'Le Talisman s’associe automatiquement à un Héros de force ≤ 3 et revient libre quand ce Héros est éliminé. Forme de grenouille s’associe à un Héros (−2 force) ; un Héros de force 0 peut être éliminé sans Allié. Poudre d’illusion vide la pile à chaque Héros éliminé.',
      'Choix interactifs : Divination (ordre de résolution), Tour de passe-passe (carte gardée), Si près du but / Charlotte (cartes envoyées dans la pile + ordre), Poupées vaudou (déplacer un Héros), Canne (agir sur un lieu voisin). Joujou peut cibler les Esprits des masques (Allié + Objet) ; Ray laisse jouer la 2ᵉ carte révélée.',
      'Conditions Désespoir / Terreur ; Lawrence suit les Héros, l’Ombre suit le pion, Tiana renchérit les cartes, Big Daddy/Eudora/Naveen actifs.',
      'Règles : Forêt de Ronces ne peut plus être posée sur un lieu où un Héros présent viole sa restriction ; Joyeux non-anniversaire est injouable sans Allié dans le royaume.',
      'Améliorations du bot : il n’utilise plus Alignement des planètes sans Titan entravé ni Joyeux non-anniversaire sans Allié, et peut défausser d’un coup les cartes injouables.',
      'Menu : nouveau fond d’écran Disney Villainous et nouvelle musique (« The Magic Mirror »). Liste des villains affichée en rangées de 4.',
    ],
  },
  {
    version: '0.59',
    date: '2026-06-13',
    title: 'Sons : voix d’intro + banque de sons',
    changes: [
      'À l’entrée d’une partie, une séquence vocale se joue : voix de votre méchant, « Contre », puis voix du méchant adverse (une variante tirée au hasard parmi quatre à chaque fois).',
      'Nouvelle page « Banque de sons » accessible depuis le menu principal : parcourir et écouter tous les sons (recherche, filtre par catégorie, précédent/suivant, lecture automatique enchaînée, volume).',
    ],
  },
  {
    version: '0.58',
    date: '2026-06-13',
    title: 'Refonte de l’interface + couleurs des méchants',
    changes: [
      'Les panneaux des deux camps (nom, jetons, objectif) sont regroupés en bas de l’écran, de part et d’autre de la main ; colonnes des plateaux agrandies, textes d’objectif et jetons plus grands.',
      'Couleur thématique de chaque méchant appliquée partout : fonds des cases et des panneaux, contours des cases / du plateau / du pion, serpent du lieu courant, bulles du journal.',
      'Main du bot affichée en éventail (dos cachés) ; piles Fatalité (pioche + défausse) regroupées à gauche des cases Héros, zoom de défausse repositionné.',
      'Les actions jouées par le bot s’illuminent une par une sur son plateau ; le passage à votre tour attend désormais la fin des showcases adverses.',
      'Showcase de défausse affiché en niveaux de gris pour mieux l’identifier.',
      'En-tête épuré : titre centré en majuscules avec effet brillance, boutons « Mode test » et « Quitter le test », sélecteur de vilains réservé au mode test.',
      'Correctif : le bot Slenderman ne joue plus Téléportation ni Brouillage en l’absence de Héros dans son royaume.',
    ],
  },
  {
    version: '0.57',
    date: '2026-06-12',
    title: 'Nouveau vilain : Hadès',
    changes: [
      'Hadès (Disney, 3★) jouable : objectif « avoir 3 Titans non entravés sur le Mont Olympe au début de votre tour ».',
      'Mécanique des Titans : joués sur Les Enfers, amenés vers l’Olympe gratuitement via « Déplacer un Objet ou un Allié » (1 lieu), ou en payant via « Préparez-vous au combat ! » (2 JT/1 lieu, 5 JT/2 lieux). Argès rend du Pouvoir, Pyros et Alignement des planètes désentravent, Stratos déplace un Héros.',
      'Entrave par la Fatalité : Zeus (à l’arrivée), Héra, Éclairs ; Hercule verrouille les Titans sur son lieu ; Pégase et De zéro en héros les repoussent.',
      'Cerbère frappe à distance, l’Hydre revient en main, Nessus rapporte du Pouvoir, Panique réduit les coûts, Potion de mortalité préserve les Titans, Talon d’Achille et le Médaillon ajustent la force.',
      'Le Char déplace ta figurine (et lui-même) vers n’importe quel lieu une fois par tour. Stratos/Mégara/Hermès (déplacer un Héros), Héra/Pégase (entraver/repousser un Titan) et le Vanquish bonus de Lythos sont des choix interactifs.',
      'Pion détouré, plateau, 30 cartes Méchant + 15 Fatalité, fiche et conseils.',
    ],
  },
  {
    version: '0.56',
    date: '2026-06-12',
    title: 'Correctif : Objets Fatalité associés à un Héros',
    changes: [
      'Provocation (Crochet) s’associe désormais réellement au Héros choisi lors d’une Fatalité — Crochet doit alors éliminer les Héros provocateurs en premier (la règle d’ordre était déjà en place, mais la carte n’était jamais posée).',
      'Même correctif générique pour tous les Objets Fatalité « associés à un Héros » qui étaient silencieusement défaussés : Poussière de Fée, Vœu, Bigette Bulbeuse, Zirgouflex.',
    ],
  },
  {
    version: '0.55',
    date: '2026-06-12',
    title: 'Ursula : effets de cartes (presque tout)',
    changes: [
      'Divination (chercher un Pacte), Opportunisme (reprendre un Objet/Événement en défausse), Polochon (remélanger la défausse Vilain).',
      'Conditions Arrogance (piocher 3 / défausser 3) et Illusion (jouer la Fatalité adverse).',
      'Héros Fatalité : Max (déplace la figurine d’Ursula), Sébastien (vole un Pacte), Eurêka (récupère un Objet), Ariel (gèle un Objet : Ursula ne peut plus le déplacer).',
      'Âmes en Perdition déclenche les Pactes des lieux voisins.',
      'Colère Titanesque : effectuez une action d’un lieu voisin (vous choisissez le lieu, puis agissez dessus). Ursula est désormais complète.',
    ],
  },
  {
    version: '0.54',
    date: '2026-06-12',
    title: 'Ursula : Pactes, Trident, Chaudron',
    changes: [
      'Pacte : un Héros portant un Pacte est éliminé dès qu’il est déplacé sur le lieu du Pacte (il emporte ses Objets associés en se déplaçant).',
      'Trident : sa pose invoque le Roi Triton (zone haute) et lui associe le Trident ; vaincre Triton libère le Trident (zone basse) pour l’amener au Repaire.',
      'Tourbillon / Flotsam / Jetsam : déplacent un Héros (Tourbillon sur n’importe quel lieu) — de quoi déclencher les Pactes.',
      'Chaudron : +2 Pouvoir par Pacte dans le royaume.',
    ],
  },
  {
    version: '0.53',
    date: '2026-06-12',
    title: 'Nouveau vilain : Ursula',
    changes: [
      'Ursula (Disney, 5★) jouable : objectif « avoir le Trident et la Couronne au Repaire d’Ursula ».',
      'Palais bloqué au départ ; le Cadenas se déplace entre le Palais et le Repaire (Métamorphose, Grimsby).',
      'Couronne (regarde 2 cartes Fatalité) et bonus de force des Objets associés câblés.',
      'Pactes, Trident (via le Roi Triton), Chaudron, Divination, etc. restent « base jouable » (effet complet à venir).',
    ],
  },
  {
    version: '0.52',
    date: '2026-06-11',
    title: 'Fatalité : Migraine Atroce + cartes non jouables grisées',
    changes: [
      'Migraine Atroce : défaussez un Objet du royaume adverse (au choix).',
      'Lors d’une Fatalité, une carte sans cible valide (ex. Migraine Atroce sans Objet) est grisée quand l’autre est jouable.',
      'Il était un Rêve n’est jouable que s’il existe une Malédiction sur un lieu portant un Héros.',
    ],
  },
  {
    version: '0.51',
    date: '2026-06-11',
    title: 'Reine de Cœur : Chute dans le terrier',
    changes: [
      'Chute dans le terrier : cherche Alice (pioche + défausse Fatalité) et la pose sur le lieu de votre choix.',
      'Si Alice est déjà dans le royaume, retirez plutôt un Allié présent sur son lieu.',
    ],
  },
  {
    version: '0.50',
    date: '2026-06-11',
    title: 'Carte du Pays Imaginaire, Trahison, Digne Adversaire',
    changes: [
      'Carte du Pays Imaginaire : cliquez dessus (à tout moment de votre tour) pour la défausser et jouer gratuitement un Objet de votre main.',
      'Trahison fait bien perdre 2 jetons Pouvoir à Jafar.',
      'Digne Adversaire / Obsession : le Héros révélé doit être joué (vous choisissez seulement le lieu) ; les autres cartes dévoilées sont défaussées.',
    ],
  },
  {
    version: '0.49',
    date: '2026-06-11',
    title: 'Jafar : Abu/Aladdin, K.O., Hypnose = Vaincre',
    changes: [
      'Abu / Aladdin : vous choisissez l’Objet à voler (du lieu, et de la main pour Aladdin) ; il est associé au Héros, inutilisable par Jafar.',
      'K.O. : vous choisissez l’Allié de force ≤ 3 à retirer du royaume.',
      'Hypnose est désormais traitée comme « éliminer un Héros » : elle déclenche les Conditions adverses (Obsession, Méchanceté, Crise d’hystérie) selon la force du Héros hypnotisé.',
      'Digne Adversaire / Obsession : le Héros dévoilé peut être joué (vous choisissez le lieu) ou défaussé ; les autres cartes dévoilées sont montrées avant d’être défaussées.',
      'Zoom au survol des cartes dans la fenêtre de défausse.',
    ],
  },
  {
    version: '0.48',
    date: '2026-06-11',
    title: 'Crochet : Pas de Quartier ! interactif + Flibustiers',
    changes: [
      'Pas de Quartier ! : vous choisissez désormais quel Allié déplacer, puis sa destination (lieu voisin non bloqué), avant de gagner +2 force.',
      'Flibustiers : ils peuvent bien être sélectionnés pour éliminer un Héros d’un lieu voisin (côte à côte) — la sélection à l’écran le proposait pas.',
    ],
  },
  {
    version: '0.47',
    date: '2026-06-11',
    title: 'Crochet : Faites-leur peur ! interactif',
    changes: [
      'Faites-leur peur ! ouvre une fenêtre montrant les 2 premières cartes Fatalité : défaussez-les ou remettez-les sur le dessus dans l’ordre de votre choix.',
      'Correction : dos de cartes du Capitaine Crochet (Vilain ↔ Fatalité) remis dans le bon sens.',
    ],
  },
  {
    version: '0.46',
    date: '2026-06-11',
    title: 'Crochet : actions accordées cliquables sur la carte',
    changes: [
      'La Boîte à Crochets (et le Canon, l’Ingénieux Mécanisme) : l’action accordée se déclenche en cliquant directement sur la carte posée (badge « ▶ action » + contour jaune), au lieu d’une pastille au centre du lieu.',
    ],
  },
  {
    version: '0.45',
    date: '2026-06-11',
    title: 'Capitaine Crochet : effets complets',
    changes: [
      'Objets qui donnent une action au lieu : Canon (Éliminer), Boîte à Crochets (Gagner 1), Ingénieux Mécanisme (Déplacer un Héros).',
      'Peter Pan se place d’office sur l’Arbre du Pendu dès qu’il est dévoilé (même verrouillé).',
      'Digne Adversaire & Obsession : piochent un Héros dans votre propre deck Fatalité et le jouent.',
      'Monsieur Starkey (déplacer un Héros), Clochette (défausser un Allié), Tic Tac (défausse de la main), Pas de Quartier ! (+2 force), Faites-leur peur !, Ruse.',
    ],
  },
  {
    version: '0.44',
    date: '2026-06-11',
    title: 'Nouveau vilain : Capitaine Crochet',
    changes: [
      'Capitaine Crochet (Disney, 3★) jouable : objectif « éliminer Peter Pan sur le Jolly Roger ».',
      'Arbre du Pendu verrouillé au départ, débloqué par la Carte du Pays Imaginaire.',
      'Enfants Perdus (2 Alliés requis), Flibustiers (Vaincre à distance), Provocation (ordre d’élimination), bonus de force (Mouche, Wendy, Jean, Michel, Sabre, Poussière de Fée).',
      'Certains effets restent « base jouable » (Canon/Boîte/Ingénieux donnant une action, Digne Adversaire/Obsession, Faites-leur peur, etc.).',
    ],
  },
  {
    version: '0.43',
    date: '2026-06-11',
    title: 'Correctif : fenêtre du Coup Royal',
    changes: [
      'La fenêtre de résultat du Coup Royal peut de nouveau se fermer après une victoire (elle restait bloquée car la partie était déjà terminée).',
    ],
  },
  {
    version: '0.42',
    date: '2026-06-11',
    title: 'Reine de Cœur : arceaux & Lance',
    changes: [
      'Par ordre de la Reine ! : transformez 1 ou 2 Cartes Gardes en arceaux (sélection à l’écran ; le Dodo protège les Gardes de son lieu).',
      'La Lance donne bien +1 Force, et peut être associée à un arceau (correction : c’était autorisé) — un arceau renforcé est plus dur à franchir au Coup Royal.',
      'L’IA Reine de Cœur transforme ses Cartes Gardes en priorité sur les lieux sans arceau.',
    ],
  },
  {
    version: '0.41',
    date: '2026-06-11',
    title: 'Reine de Cœur : Agrandir',
    changes: [
      'Agrandir (Fatalité) : un Héros agrandi recouvre les 2 actions de son lieu PLUS une action d’un lieu voisin (le côté le plus gênant est choisi).',
      'Agrandir sur un Héros rapetissé le ramène à sa taille normale.',
    ],
  },
  {
    version: '0.40',
    date: '2026-06-11',
    title: 'IA Jafar & Lance',
    changes: [
      'Le bot Jafar pose le Scarabée d’Or (déverrouillage) puis la Lampe Merveilleuse (Génie) dès que possible.',
      'La Lance ne peut plus être associée à un arceau (Cartes Gardes transformées).',
    ],
  },
  {
    version: '0.39',
    date: '2026-06-11',
    title: 'Joyeux non-anniversaire',
    changes: [
      'Joyeux non-anniversaire donne bien 1 Pouvoir par Allié du royaume (arceaux inclus).',
    ],
  },
  {
    version: '0.38',
    date: '2026-06-11',
    title: 'Reine de Cœur : Rapetisser',
    changes: [
      'Rapetisser : un Héros rapetissé ne recouvre qu’une des 2 actions du haut — vous choisissez laquelle utiliser.',
      'Rapetisser sur un Héros agrandi le ramène à sa taille normale ; le Loir ne peut pas rapetisser.',
    ],
  },
  {
    version: '0.37',
    date: '2026-06-11',
    title: 'Reine de Cœur : Coup Royal',
    changes: [
      'Coup Royal jouable : si un arceau est sur chaque lieu, on révèle 5 cartes ; si leurs coûts < force des arceaux, victoire !',
      'Une fenêtre montre les 5 cartes révélées et le verdict (réussi/raté).',
    ],
  },
  {
    version: '0.36',
    date: '2026-06-11',
    title: 'Reine de Cœur : arceaux',
    changes: [
      'Action Activer : transformez une Carte Garde en arceau (et inversement) ; un arceau compte comme Allié mais ne peut pas éliminer de Héros.',
      'Le Lapin Blanc (+1 coût) et Dodo (blocage sur son lieu) sont pris en compte.',
      'Bruitages encore réduits ; dos de cartes de la Reine de Cœur corrigés.',
    ],
  },
  {
    version: '0.35',
    date: '2026-06-11',
    title: 'Nouveau vilain : Reine de Cœur',
    changes: [
      'Reine de Cœur jouable : plateau, 27 cartes et illustrations.',
      'Objectif : placer un arceau dans chaque lieu et réussir un Coup Royal.',
      'Bruitages moins forts par défaut.',
      'En cours : transformation des Cartes Gardes en arceaux et victoire par Coup Royal.',
    ],
  },
  {
    version: '0.34',
    date: '2026-06-11',
    title: 'Options : volume des bruitages',
    changes: [
      'Réglage séparé du volume des bruitages (sons d’interface) dans les Options.',
    ],
  },
  {
    version: '0.33',
    date: '2026-06-11',
    title: 'Son de clic',
    changes: [
      'Un petit son est joué à chaque clic sur un bouton.',
    ],
  },
  {
    version: '0.32',
    date: '2026-06-11',
    title: 'Profil : historique des parties',
    changes: [
      'Le profil liste l’historique des parties : quel vilain contre quel vilain, et le vainqueur.',
    ],
  },
  {
    version: '0.31',
    date: '2026-06-11',
    title: 'Jafar : conseils & stratégie du bot',
    changes: [
      'Fiche de Jafar : conseils « bien le jouer » et « le contrer » réécrits.',
      'Le bot suit mieux le combo de Jafar (déverrouiller la Caverne → invoquer le Génie → rapprocher la Lampe du Palais → hypnotiser).',
    ],
  },
  {
    version: '0.30',
    date: '2026-06-11',
    title: 'Options musique + fond du menu net',
    changes: [
      'Nouvelle option : couper la musique quand le jeu n’est pas au premier plan (autre onglet/fenêtre).',
      'L’image de fond du menu principal n’est plus floutée.',
    ],
  },
  {
    version: '0.29',
    date: '2026-06-11',
    title: 'Musique du menu',
    changes: [
      'La musique « Magic Mirror » joue en boucle dans les écrans du menu (volume/sourdine dans les Options).',
    ],
  },
  {
    version: '0.28',
    date: '2026-06-11',
    title: 'Lampe (Caverne) & Sacrifice (objets associés)',
    changes: [
      'La Lampe Merveilleuse ne peut être posée que sur la Caverne aux Merveilles.',
      'Sacrifice Nécessaire peut défausser un Objet associé à un Allié ou à un Héros hypnotisé.',
    ],
  },
  {
    version: '0.27',
    date: '2026-06-11',
    title: 'Tromperie, Manipulation & Cimeterre',
    changes: [
      'Tromperie : vous choisissez désormais où poser le Héros Fatalité révélé.',
      'Manipulation : une fenêtre affiche votre défausse pour choisir la carte à reprendre.',
      'Cimeterre peut être associé à un Héros hypnotisé (il compte comme un Allié) : +1 force.',
    ],
  },
  {
    version: '0.26',
    date: '2026-06-11',
    title: 'Iago : choix de l’objet à emmener',
    changes: [
      'Si plusieurs objets sont sur le lieu d’Iago, une fenêtre demande lequel emmener (ou « Iago seul »).',
    ],
  },
  {
    version: '0.25',
    date: '2026-06-11',
    title: 'Jafar : Sablier Géant + barre d’objectif',
    changes: [
      'Sablier Géant (Activer) : les Héros de son lieu ont −2 force jusqu’à la fin de votre tour.',
      'La barre d’objectif de Jafar affiche sa vraie progression (Génie contrôlé + Lampe au Palais).',
    ],
  },
  {
    version: '0.24',
    date: '2026-06-11',
    title: 'Options : mode d’affichage',
    changes: [
      'Nouveau réglage d’affichage : Fenêtré, Plein écran, Plein écran fenêtré.',
    ],
  },
  {
    version: '0.23',
    date: '2026-06-11',
    title: 'Corrections : Disparition & Tromperie',
    changes: [
      'Correction : la Disparition de Maléfique s’affichait avec la carte de Slenderman (collision d’identifiant).',
      'Tromperie : les Malédictions de Maléfique comptent comme des Objets pour son déclencheur (≥2 Objets).',
      'Correction : le bouton « jouer une Condition » (Tromperie, Manipulation…) ne réagissait pas.',
      'Tromperie : dévoile et joue la 1ʳᵉ Fatalité de l’adversaire contre lui. Manipulation : reprend une carte de votre défausse.',
    ],
  },
  {
    version: '0.22',
    date: '2026-06-11',
    title: 'Choix du vilain adverse + aléatoire',
    changes: [
      'Nouvelle partie : choisis ton vilain ET celui de l’adversaire (bot).',
      'Option « 🎲 Aléatoire » pour chaque camp (l’adversaire aléatoire évite le miroir).',
    ],
  },
  {
    version: '0.21',
    date: '2026-06-11',
    title: 'Lancer de dé : qui commence',
    changes: [
      'Au début de chaque partie, chaque joueur lance un 1d20 (animé) : le plus haut score commence.',
      'En cas d’égalité, on relance automatiquement.',
      'Le joueur qui ne commence pas démarre avec 1 jeton Pouvoir (compensation).',
    ],
  },
  {
    version: '0.20',
    date: '2026-06-11',
    title: 'Scarabée d’Or : pioche jusqu’à 5',
    changes: [
      'Tant que le Scarabée d’Or est sur votre plateau, vous complétez votre main à 5 cartes au lieu de 4.',
      'Symétriquement, la Princesse Jasmine (Fatalité) réduit la limite de 1.',
    ],
  },
  {
    version: '0.19',
    date: '2026-06-11',
    title: 'Animation de pioche + Héros hypnotisé',
    changes: [
      'Pioche : les nouvelles cartes « volent » de la pioche vers la main au lieu d’apparaître instantanément.',
      'Un Héros hypnotisé (Jafar) s’affiche désormais dans la zone basse (côté méchant), comme un Allié.',
    ],
  },
  {
    version: '0.18',
    date: '2026-06-11',
    title: 'Jafar : Hypnose & co',
    changes: [
      'Hypnose : prenez le contrôle d’un Héros de votre royaume (coût = sa force) ; il devient un Allié et ne recouvre plus les actions — clé de la victoire.',
      'Sceptre Serpent (Activer) : payez 1 Pouvoir pour récupérer une carte Hypnose de votre défausse.',
      'Razoul : jouer un Allié sur son lieu coûte 1 Pouvoir de moins.',
      'Ah, je suis un serpent ? : la cible doit être sur votre lieu (corrigé).',
    ],
  },
  {
    version: '0.17',
    date: '2026-06-11',
    title: 'Voir sa défausse',
    changes: [
      'Cliquer sur une pile de défausse ouvre la liste de toutes les cartes qu’elle contient (plus récentes en premier).',
    ],
  },
  {
    version: '0.16',
    date: '2026-06-11',
    title: 'Jafar : Sacrifice Nécessaire',
    changes: [
      'Sacrifice Nécessaire : défaussez un Allié ou un Objet de votre royaume pour gagner 3 Pouvoir.',
    ],
  },
  {
    version: '0.15',
    date: '2026-06-11',
    title: 'Jafar : Prédiction',
    changes: [
      'Prédiction : choisissez Objet ou Allié, on révèle la pioche jusqu’à en trouver un, gardé en main ; le reste est défaussé.',
    ],
  },
  {
    version: '0.14',
    date: '2026-06-11',
    title: 'Jafar : action « Activer » + Iago',
    changes: [
      'Nouvelle action de lieu « Activer » (symbole nuage/éclair) sur le plateau de Jafar.',
      'Capacité activée d’Iago : payez 1 Pouvoir pour déplacer Iago et un Objet de son lieu vers un lieu voisin.',
      'Les lieux verrouillés ne peuvent être ni cible ni source d’un déplacement (règle officielle).',
    ],
  },
  {
    version: '0.13',
    date: '2026-06-11',
    title: 'Fiche vilain : voir les cartes',
    changes: [
      'Dans la fiche d’un vilain, un bouton « Voir toutes les cartes » affiche son deck Vilain et Fatalité.',
      'Chaque carte indique son nombre d’exemplaires (×N).',
    ],
  },
  {
    version: '0.12',
    date: '2026-06-11',
    title: 'Nouveau vilain : Jafar',
    changes: [
      'Jafar est jouable : plateau, 27 cartes (Vilain + Fatalité) et illustrations.',
      'Objectif : contrôler le Génie (Hypnose) avec la Lampe Merveilleuse au Palais du Sultan.',
      'Caverne aux Merveilles verrouillée, déverrouillée par le Scarabée d’Or ; la Lampe invoque le Génie.',
      'Bonus de force câblés (Cimeterre, Vœu, Génie+Lampe, Rajah+Jasmine).',
      'En cours : l’Hypnose (prise de contrôle) et plusieurs capacités activées arrivent prochainement.',
    ],
  },
  {
    version: '0.11',
    date: '2026-06-11',
    title: 'Main en éventail',
    changes: [
      'La main du joueur est désormais ancrée en bas de l’écran, en éventail (style jeu de cartes en ligne).',
      'Survol d’une carte : elle se relève et se redresse pour être lisible.',
    ],
  },
  {
    version: '0.10',
    date: '2026-06-11',
    title: 'Écran de profil',
    changes: [
      'Nouveau menu « Mon profil » : statistiques par vilain.',
      'Suivi du temps de jeu, des victoires/défaites et du % de victoire.',
      'Statistiques sauvegardées entre les sessions ; réinitialisation possible.',
    ],
  },
  {
    version: '0.9.1',
    date: '2026-06-11',
    title: 'Menu principal : nouvelle ambiance',
    changes: [
      'Image de fond floutée (avec voile sombre) sur le menu principal.',
    ],
  },
  {
    version: '0.9',
    date: '2026-06-11',
    title: 'Slenderman : tous les effets',
    changes: [
      'Dessin inquiétant : +1 pouvoir par Page sur votre lieu.',
      'Brouillage : utiliser une action recouverte par un Héros.',
      'Téléportation : déplacer le pion sur un lieu à Héros, puis y jouer.',
      'Apparition / Vent de panique : déplacer un Héros vers un lieu voisin.',
      'Lampe de poche : bloque la téléportation vers le Héros équipé.',
      'Lever du jour : empêche de jouer une Page au prochain tour.',
      'Mauvaise creepypasta : ramène votre réserve à 2 jetons.',
      'Sombres desseins / Sans visage : Conditions déclenchées par les actions adverses.',
    ],
  },
  {
    version: '0.8',
    date: '2026-06-11',
    title: 'Slenderman : Disparition',
    changes: [
      'Disparition : élimine sans allié un Héros présent sur le lieu de Slenderman.',
    ],
  },
  {
    version: '0.7',
    date: '2026-06-11',
    title: 'Règles & habillage',
    changes: [
      'Page : maximum 2 par lieu (règle appliquée à la pose).',
      'Volume de la musique plafonné pour un fond plus discret.',
      'Menu principal repensé : titre agrandi, boutons centrés, panneau de notes en haut à gauche.',
    ],
  },
  {
    version: '0.6',
    date: '2026-06-11',
    title: 'Audio & options',
    changes: [
      'Musique « Slender: The Arrival » pendant le tour de Slenderman.',
      'Bouton Options : réglage du volume de la musique et sourdine (mémorisés).',
      'Ajout de ce panneau de notes de version dans le menu.',
    ],
  },
  {
    version: '0.5',
    date: '2026-06-11',
    title: 'Slenderman : mécaniques',
    changes: [
      'Retourne-toi : voir la dernière carte de la pioche, la garder ou remélanger + piocher.',
      'Perdu dans les bois : mélange défausse + pioche, puis pioche 2 cartes.',
      'Tombée de la nuit : choix Événement/Objet, on garde la 1ʳᵉ des 4 cartes dévoilées.',
      "Action « Déplacer un héros » (Maison Perdue) — le bot l'utilise s'il y gagne.",
      'Enquêteur / Enfant Perdu capturent les Pages ; le bot les pose en priorité sur les Pages.',
    ],
  },
  {
    version: '0.4',
    date: '2026-06-11',
    title: 'Nouveau vilain : Slenderman',
    changes: [
      'Slenderman jouable : plateau, objectif « 8 Pages dans le royaume », 45 cartes.',
      'Jauge d’objectif dédiée (Pages X / 8).',
      'Actions du plateau cliquables comme pour les autres vilains.',
    ],
  },
  {
    version: '0.3',
    date: '2026-06-11',
    title: 'Menu & encyclopédie',
    changes: [
      'Menu principal (Nouvelle partie, Liste des villains) avec le logo du jeu.',
      'Écran de choix du vilain avant de lancer la partie.',
      'Fiches vilains : difficulté en étoiles, objectif, histoire, conseils pour jouer/contrer.',
    ],
  },
]
